import Head from "next/head";
import { useEffect } from "react";
import { useRouter } from "next/navigation";

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    setTimeout(() => {
      router.push("/data");
    }, 1000);
  }, []);
  return (
    <>
      <Head>
        <title>PADO</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-32 flex h-full w-full items-center justify-center">
        <h1 className="text-7xl font-extrabold ">Welcome</h1>
      </div>
    </>
  );
}
